- name: ':sparkles: feature'
  color: 5319E7
  description: 'A new feature'
- name: ':bug: bug'
  color: D73A4A
  description: 'A bug fix'
- name: ':memo: documentation'
  color: 0075CA
  description: 'Documentation only changes'
- name: ':art: style'
  color: CFD3D7
  description: 'Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)'
- name: ':recycle: refactor'
  color: 03BC5E
  description: 'A code change that neither fixes a bug nor adds a feature'
- name: ':test_tube: test'
  color: A2EEEF
  description: 'Adding missing tests or correcting existing tests'
- name: ':wrench: chore'
  color: 5fBCA04
  description: 'Changes to the build process or auxiliary tools and libraries such as documentation generation'
- name: ':bookmark: release'
  color: E99695
  description: 'Create a release commit'
- name: ':question: question'
  color: CC317C
  description: 'Further information is requested'
- name: ':construction_worker: ci/cd'
  color: 64B5F6
  description: 'Changes to our CI/CD configuration files and scripts'
