spring:
  config:
    activate:
      on-profile: "auth"

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirectUri: "http://localhost:8080/api/oauth2/login/callback/google"
            scope:
              - email
              - profile

## JWT
jwt:
  bearer: ${JWT_BEARER:Bearer}
  secret: ${JWT_SECRET_KEY}
  access-expiration: ${JWT_ACCESS_EXPIRE:3600000} # 1시간
  access-header: ${JWT_ACCESS_HEADER:Authorization} # Access Token 헤더
  refresh-expiration: ${JWT_REFRESH_EXPIRE:86400000} # 1일
  refresh-header: ${JWT_REFRESH_HEADER:Authorization-refresh} # Refresh Token 헤더
