spring:
  config:
    activate:
      on-profile: "local"

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true

## local 환경 = debug
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
