server:
  port: ${APP_PORT:8080}

spring:
  application:
    name: Say Better

  jpa:
    open-in-view: false

  profiles:
    group:
      "local": "local, auth, local-datasource, docs"
      "dev": "dev, auth, dev-datasource, docs"
