server:
  port: ${APP_PORT:8080}

spring:
  application:
    name: Say Better

  jpa:
    open-in-view: false

  profiles:
    group:
      "local": "local, auth, redis, local-datasource, docs, api"
      "dev": "dev, auth, redis, dev-datasource, docs, api"
