spring:
  config:
    activate:
      on-profile: "api"

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000

## recommend
recommend:
  api:
    base-url: ${RECOMMEND_API_BASE_URL}
    identity-token: ${RECOMMEND_API_IDENTITY_TOKEN}
