version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: rabbitmq-stream
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  spring-app:
    image: saybetter/springboot-dev:latest
    container_name: spring-app
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq

  reverse-proxy:
    image: nginx
    container_name: reverse-proxy
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - "80:80"
    depends_on:
      - spring-app
