spring:
  data:
    redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

---
spring.config.activate.on-profile:
  - local

---
spring.config.activate.on-profile:
  - local-dev
  - dev
