name: 🎨 Checkstyle

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]


jobs:
  checkstyle:
    name: checkstyle
    runs-on: ubuntu-latest # ubuntu-22.04

    strategy:
      matrix:
        java: [ 17 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          architecture: x64
          cache: "gradle"

      - name: Run Checkstyle
        uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-review'
          tool_name: 'Checkstyle for Java'
          checkstyle_config: rule-config/naver-checkstyle-rules.xml
          properties_file: rule-config/additional.properties
          level: warning
