name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  PROJECT_ID: ${{ secrets.GCE_PROJECT_ID }}
  INSTANCE_NAME: ${{ secrets.GCE_INSTANCE_NAME }}
  INSTANCE_ZONE: ${{ secrets.GCE_INSTANCE_ZONE }}
  SA_KEY: ${{ secrets.GCE_SA_KEY }}
  CONTAINER_NAME: say-better
  ENV_FILE: ${{ secrets.SERVER_ENV_FILE }}

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Gradle 캐싱 빌드 시간 향상
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute Permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/say-better:latest

  deploy:
    name: CD
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: google auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ env.SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Use gcloud CLI
        run: gcloud init

      - name: Deploy to GCE
        run: |-
          gcloud compute ssh \
          --project ${{ env.PROJECT_ID }} \
          --zone ${{ env.INSTANCE_ZONE }} ${{ env.INSTANCE_NAME }} 
          
          docker -v
          docker ps
          docker pull ${{ env.DOCKERHUB_USERNAME }}/say-better:latest
          docker run -d -p 8080:8080 \
                --name ${{ env.CONTAINER_NAME }} \
                --env-file ${{ env.ENV_FILE }} ${{ env.DOCKERHUB_USERNAME }}/say-better:latest
          docker ps
